apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
spec:
  containers:
    - name: readiness-demo-container
      image: nginx
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 30
