apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    app: myservice
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30007 # Optional: Specify if you want a specific node port
