apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: sidecar
      image: busybox
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do echo 'Sidecar container running...'; sleep 10; done",
        ]
