apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-demo
spec:
  containers:
    - name: liveness-exec-demo-container
      image: busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 10
