apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
spec:
  containers:
    - name: liveness-demo-container
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
